//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWpf
{
    
    internal partial class Resource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new System.Resources.ResourceManager("SimpleWpf.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static nanoFramework.UI.Bitmap GetBitmap(Resource.BitmapResources id)
        {
            return ((nanoFramework.UI.Bitmap)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static nanoFramework.UI.Font GetFont(Resource.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resource.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            courierregular10 = -25095,
            small = 13070,
            NinaB = 18060,
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            Scrollable_Panel_Icon = -20164,
            Diagonal_Panel_Icon = -16011,
            Canvas_Panel_Icon = -9105,
            Vertical_Stack_Panel_Icon = -7672,
            Horizontal_Stack_Panel_Icon_Small = -6042,
            Diagonal_Panel_Icon_Small = 2069,
            Scrollable_Panel_Icon_Small = 4749,
            Free_Drawing_Panel_Icon = 4854,
            Free_Drawing_Panel_Icon_Small = 15133,
            Horizontal_Stack_Panel_Icon = 15925,
            Canvas_Panel_Icon_Small = 20403,
            Vertical_Stack_Panel_Icon_Small = 31390,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            DrawTextSample = -12253,
            MenuScrolling = -8879,
            MenuSelection = 9947,
            ScrollableTextTitle = 14311,
            ReturnToMenu = 29183,
            ScrollableText = 31192,
        }
    }
}
