//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "NF_AwesomeLib.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_NF_AwesomeLib_NF_AwesomeLib_Math::NativeSuperComplicatedCalculation___STATIC__R8__R8,
    NULL,
    NULL,
    Library_NF_AwesomeLib_NF_AwesomeLib_Utilities::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_AwesomeLib =
{
    "NF.AwesomeLib", 
    0xBB94F141,
    method_lookup,
    { 1, 0, 0, 0 }
};
