//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using nanoFramework.UI;

namespace Tetris
{
    
    internal partial class nfResource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((nfResource.manager == null))
                {
                    nfResource.manager = new System.Resources.ResourceManager("NanoTetris.nfResource", typeof(nfResource).Assembly);
                }
                return nfResource.manager;
            }
        }
        internal static nanoFramework.UI.Font GetFont(nfResource.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(nfResource.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static Bitmap GetBitmap(nfResource.BitmapResources id)
        {
            return ((nanoFramework.UI.Bitmap)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Consolas23 = -31666,
            NinaB = 18060,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            LinesCompleted = -27201,
            HighScore = -22559,
            PressAnyKey = -21048,
            ExtremeLevel = -20249,
            Level = -13726,
            Score = -13075,
            AdvancedLevel = -11619,
            GameOver = -10866,
            PressSelect = -9962,
            UseArrows = -8823,
            RookieLevel = 9176,
            ViewHighScore = 13410,
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            Logo = 16403,
        }
    }
}
