//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef _NF_AWESOMELIB_H_
#define _NF_AWESOMELIB_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>

struct Library_NF_AwesomeLib_NF_AwesomeLib_Math
{
    NANOCLR_NATIVE_DECLARE(NativeSuperComplicatedCalculation___STATIC__R8__R8);

    //--//

};

struct Library_NF_AwesomeLib_NF_AwesomeLib_Utilities
{
    static const int FIELD_STATIC___hardwareSerial = 0;

    NANOCLR_NATIVE_DECLARE(NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1);

    //--//

};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_AwesomeLib;

#endif  //_NF_AWESOMELIB_H_
