//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using nanoFramework.UI;
using System;

namespace Primitives
{
    
    internal partial class Resource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new System.Resources.ResourceManager("Primitives.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static nanoFramework.UI.Bitmap GetBitmap(Resource.BitmapResources id)
        {
            return ((nanoFramework.UI.Bitmap)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static nanoFramework.UI.Font GetFont(Resource.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resource.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            strnSmallFont = -19509,
            strComicSansMS16 = -18892,
            strNinaFont = 10925,
            strCourierRegular10 = 19139,
            strSegoeUIRegular12 = 25622,
        }

        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            ComicSansMS16 = -18137,
            SegoeUIRegular12 = 11243,
            small = 13070,
            NinaB = 18060,
            CourierRegular10 = 27752,
            MatrixFont = 28174,
        }
        internal enum BitmapResources : short
        {
        }

    }
}
